websites = {
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "facebook": "https://www.facebook.com",
    "twitter": "https://www.twitter.com",
    "instagram": "https://www.instagram.com",
    "wikipedia": "https://www.wikipedia.org",
    "amazon": "https://www.amazon.com",
    "yahoo": "https://www.yahoo.com",
    "reddit": "https://www.reddit.com",
    "netflix": "https://www.netflix.com",
    "stackoverflow": "https://stackoverflow.com",
    "github": "https://github.com",
    "gitlab": "https://gitlab.com",
    "bitbucket": "https://bitbucket.org",
    "hackerrank": "https://www.hackerrank.com",
    "leetcode": "https://leetcode.com",
    "codecademy": "https://www.codecademy.com",
    "freecodecamp": "https://www.freecodecamp.org",
    "dev.to": "https://dev.to",
    "medium": "https://medium.com", "coursera":
    "https://www.coursera.org",
    "edx": "https://www.edx.org",
    "khanacademy": "https://www.khanacademy.org",
    "quizlet": "https://quizlet.com",
    "chegg": "https://www.chegg.com",
    "scholar.google": "https://scholar.google.com",
    "udemy": "https://www.udemy.com",
    "ratemyprofessors": "https://www.ratemyprofessors.com",
    "studentloanhero": "https://studentloanhero.com",
    "collegeboard": "https://www.collegeboard.org",
    "flipkart": "https://www.flipkart.com",
    "irctc": "https://www.irctc.co.in",
    "paytm": "https://paytm.com",
    "jio": "https://www.jio.com",
    "hotstar": "https://www.hotstar.com",
    "zomato": "https://www.zomato.com",
    "ndtv": "https://www.ndtv.com",
    "cricbuzz": "https://www.cricbuzz.com",
    "indiatimes": "https://www.indiatimes.com",
    "bookmyshow": "https://in.bookmyshow.com"
}
